export default {
  "pages/tabbar/home/index": "首页",
  "pages/tabbar/course-ware/index": "课件",
  "pages/tabbar/answer/index": "答题",
  "pages/tabbar/profile/index": "我的",
  "pages/home/detail/index": "文章详情",
  // "pages/answer/index/index": "答题页面",
  // "pages/answer/form/index": "自测练习(填写表单)",
  // "pages/profile/collect/index": "我的收藏",
  // "pages/profile/success/index": "我的成绩",
  // "pages/profile/files/index": "我的档案",
  // "pages/profile/files/edit-info/index": "编辑个人信息页",
  // "pages/profile/qr-code/index": "我的二维码",
  // "pages/profile/opinion/index": "意见反馈",
  // "pages/teacher/student-list/index": "老师首页",
  "pages/teacher/student-skill/index": "我的技能",
};
